# =============================================================================
# BASE APP SETTINGS
# =============================================================================

# A function that when called should return a Transport instance. A Transport
# allows the app to communicate with the remote IDR Server and for data
# exchange to happen.
# This is a required setting.
DEFAULT_TRANSPORT_FACTORY: "app.lib.transports.http.http_transport_factory"

# The logging configuration for the app. This app use Python's built it logging.
# https://docs.python.org/3/library/logging.html
# Logging is configured during the tools general set up, i.e when `app.setup()`
# is called.
# The logging configuration provided here should conform to Python's
# `logging.config.dictConfig` format.
# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
# If this setting is not provided, then a default logging config similar to
# this on is used.
LOGGING:
  version: 1
  disable_existing_loggers: false
  formatters:
    verbose:
      format: "%(levelname)s: %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
  handlers:
    console:
      level: "DEBUG"
      class: "logging.StreamHandler"
      formatter: "verbose"
  root:
    level: "INFO"
    handlers": [ "console" ]

# The different data source types supported by the app. This determines the
# kinds of data that the app can extract and operations that can be performed
# on that data including what is uploaded to the server.
# This setting is not required and defaults to an empty list.
SUPPORTED_DATA_SOURCE_TYPES:
  - "app.imp.sql_data.SQLDataSourceType"



# =============================================================================
# HTTP TRANSPORT SETTINGS
# =============================================================================

# Configuration specific to the HTTPTransport.
# This is only required if HTTPTransport is set as the default Transport.
HTTP_TRANSPORT:
  default_http_api_dialect_factory: "app.lib.transports.http.idr_server_api_v1_dialect_factory"
  connect_timeout: 60  # 1 minutes
  read_timeout: 60 # 1 minute

# A function that when called should return a HTTPAPIDialect.
# This is only required if HTTPTransport is set as the default Transport.
DEFAULT_HTTP_API_DIALECT_FACTORY: "app.lib.http.idr_server_api_v1_dialect_factory"

# The configuration of the backend to this app. This setting is used by HTTP
# API dialects.
# This is only required if HTTPTransport is set as the default Transport.
REMOTE_SERVER:
  host: "https://idr_server.example.org"
  username: "example@test.org"
  password: "aSecurePassword123"



# =============================================================================
# SQL DATA SOURCES SETTINGS
# =============================================================================

# Configuration for SQL Data Source Type and specifically for connecting to
# MySQL databases.
# This is only required if the SQLDataSourceType is in use.
MYSQL_DB_INSTANCE:
  host: "localhost"
  port: 3306
  username: "idr_client"
  password: "securePa$$word"
