branches: ["main"]
dryRun: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/github",
      assets: [
        {path: "dist/idr_client", label: IDR Client Binary}
      ]
    ]

tagFormat: v${version}
