# =============================================================================
# BASE APP SETTINGS
# =============================================================================

# A function that when called should return a Transport instance.
DEFAULT_TRANSPORT_FACTORY: "app.lib.transports.http.http_transport_factory"

# The logging configuration for the app.
LOGGING:
  version: 1
  formatters:
    simple:
      format: "%(levelname)s: %(asctime)s %(module)s %(process)d %(message)s"
    verbose:
      format: "{levelname}: {asctime} - {process:d} {thread:d} - <module={module} | function={funcName} | line={lineno:d}> - {message}"
      style: "{"
  handlers:
    console:
      class: "logging.StreamHandler"
      formatter: "simple"
      level: "DEBUG"
    file:
      backupCount: 5
      class: "logging.handlers.RotatingFileHandler"
      encoding: "utf-8"
      filename: "logs/idr_client.log"
      formatter: "verbose"
      level: "DEBUG"
      maxBytes: 1048576  # 1 MB
  loggers:
    app:
      handlers: [ "console", "file" ]
      level: "DEBUG"
      propagate: true

# The different data source types supported by the app. This determines the
# kinds of data that the app can extract and send to a server.
SUPPORTED_DATA_SOURCE_TYPES:
  - "app.imp.sql_data.SQLDataSourceType"



# =============================================================================
# HTTP TRANSPORT SETTINGS
# =============================================================================

# Configurations for the HTTPTransport
HTTP_TRANSPORT:
  default_http_api_dialect_factory: "app.lib.transports.http.idr_server_api_v1_dialect_factory"
  connect_timeout: 60  # 1 minutes
  read_timeout: 60 # 1 minute

# A function that when called should return a HTTPAPIDialect.
DEFAULT_HTTP_API_DIALECT_FACTORY: "app.lib.http.idr_server_api_v1_dialect_factory"

# The configuration of the backend to this app. This setting is used by HTTP
# API dialects.
REMOTE_SERVER:
  host: "https://test.cbs.fahariyajamii.org"
  username: "admin"
  password: "gx7gUEze5BuxU8p"



# =============================================================================
# SQL DATA SOURCES SETTINGS
# =============================================================================

MYSQL_DB_INSTANCE:
  host: "localhost"
  port: 3306
  username: "idr_client"
  password: "securePa$$word"
