__title__ = "idr_client"
__description__ = "Just Another ETL Tool."
__url__ = "https://github.com/savannahghi/idr-client"
__version__ = "1.0.0"
__author__ = "Savannah Informatics Global Health Initiative"
__license__ = "MIT"
__copyright__ = "Copyright 2022 Savannah Informatics Global Health Initiative"
