branches: ["main"]
dryRun: false
plugins:
  - [ "@semantic-release/commit-analyzer", {
        parserOpts: {
          noteKeywords: [ "BREAKING CHANGE", "BREAKING CHANGES", "BREAKING" ],
        },
        preset: "angular",
        releaseRules: [
          { type: "chore", scope: "conf", release: "patch" },
          { type: "chore", scope: "config", release: "patch" },
          { type: "chore", scope: "core", release: "minor" },
          { type: "chore", scope: "deps", release: "patch" }
        ]
      }
    ]
  - [ "@semantic-release/release-notes-generator", {
      parserOpts: {
        noteKeywords: [ "BREAKING CHANGE", "BREAKING CHANGES", "BREAKING" ],
      },
      preset: "conventionalcommits",
      presetConfig: {
        types: [
          { type: "chore", scope: "deps", section: "Dependency Updates" },
          { type: "chore", section: "Refactors" },
          { type: "docs", hidden: true },
          { type: "feat", section: "Features" },
          { type: "fix", section: "Bug Fixes" },
          { type: "perf", hidden: true },
          { type: "refactor", section: "Refactors" },
          { type: "style", hidden: true },
          { type: "test", hidden: true }
        ]
      },
      writerOpts: {
        commitsSort: [ "subject", "scope" ],
      }
    }
  ]
  - [ "@semantic-release/changelog",
      changelogFile: "docs/CHANGELOG.md"
  ]
  - [ "@semantic-release/git", {
      assets: [ "docs/*" ],
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }
  ]
  - ["@semantic-release/github",
    assets: [
      {path: "dist/idr_client", label: IDR Client Binary}
    ]
  ]

tagFormat: v${version}
