name: Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install python3.10 nodejs
        python3.10 -m pip install -r requirements/base.txt pyinstaller~=5.2 staticx~=0.13.6

    - name: Package the app
      run: |
        python3.10 -m pyinstaller app/__main__.py --collect-all app --name idr_client_temp -F
        python3.10 -m staticx dist/idr_client_temp dist/idr_client
        ./dist/idr_client --version

    - name: Create a release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
